[postgres]
db_uri = "postgresql://postgres:TU_PASSWORD_REAL@db:5432/ferreinox_db"

[dropbox_rotacion]
app_key = "TU_APP_KEY_ROTACION"
app_secret = "TU_APP_SECRET_ROTACION"
refresh_token = "TU_REFRESH_TOKEN_ROTACION"
folder = "/data"

[dropbox_cartera]
app_key = "TU_APP_KEY_CARTERA"
app_secret = "TU_APP_SECRET_CARTERA"
refresh_token = "TU_REFRESH_TOKEN_CARTERA"
folder = "/data"

[dropbox_ventas]
app_key = "TU_APP_KEY_VENTAS"
app_secret = "TU_APP_SECRET_VENTAS"
refresh_token = "TU_REFRESH_TOKEN_VENTAS"
folder = "/data"