[dropbox_rotacion]
app_key = "TU_APP_KEY"
app_secret = "TU_APP_SECRET"
refresh_token = "TU_REFRESH_TOKEN"
folder = "/data"

[dropbox_cartera]
app_key = "TU_APP_KEY"
app_secret = "TU_APP_SECRET"
refresh_token = "TU_REFRESH_TOKEN"
folder = "/data"

[dropbox_ventas]
app_key = "TU_APP_KEY"
app_secret = "TU_APP_SECRET"
refresh_token = "TU_REFRESH_TOKEN"
folder = "/data"

[postgres]
db_uri = "postgresql://usuario:password@host:5432/base"