import pandas as pd


# Estas filas son semillas curadas de alta confianza para ampliar la lógica del catálogo.
# Son plantillas operativas para inyectar en el flujo de curación.
# Si un producto no existe en la base oficial, debe usarse como patrón de familia y no como referencia productiva final.

datos = [
    [
        "TPL_VTX_BLC_5",
        "VINILTEX BLANCO CUÑETE 1/5",
        "Pintuco",
        "Arquitectonica",
        120,
        980,
        "ventas_y_stock",
        "cuñete",
        "Blanco",
        None,
        "viniltex_blanco",
        "viniltex blanco",
        "viniltex, pintura tipo 1, viniltex blanco, viniltex cuñete",
        "cuñete, caneca, cubeta, 1/5, cunete",
        "pintulux, domestico, koraza, aerosol",
        "Tengo Viniltex Blanco. ¿Lo necesitas en cuñete, galón o cuarto?",
        "SI",
        "Priorizar esta familia por rotación. Mostrar primero la variante con stock y ventas reales.",
    ],
    [
        "TPL_VTX_BLC_1",
        "VINILTEX BLANCO GALON 1/1",
        "Pintuco",
        "Arquitectonica",
        95,
        760,
        "ventas_y_stock",
        "galon",
        "Blanco",
        None,
        "viniltex_blanco",
        "viniltex blanco",
        "viniltex, pintura tipo 1, viniltex blanco, viniltex galon",
        "galon, galón, 1/1",
        "pintulux, domestico, koraza, aerosol",
        "Tengo Viniltex Blanco. ¿Lo necesitas en cuñete, galón o cuarto?",
        "SI",
        "Debe aparecer después del cuñete si el cuñete domina ventas y stock.",
    ],
    [
        "TPL_DOM_P35_1",
        "DOMESTICO P-35 GALON 1/1",
        "Pintuco",
        "Arquitectonica",
        88,
        690,
        "ventas_y_stock",
        "galon",
        None,
        None,
        "domestico_p35",
        "domestico p-35",
        "domestico, p35, domestico p35, domestico p-35",
        "galon, galón, 1/1",
        "viniltex, pintulux, aerosol, cuarto, cuñete",
        "Tengo Doméstico P-35. ¿Lo necesitas en galón, cuarto o cuñete?",
        "SI",
        "Si el cliente no dice acabado, debe quedar pendiente para desambiguación posterior.",
    ],
    [
        "TPL_PTX_NGR_BRI_4",
        "PINTULUX NEGRO BRILLANTE CUARTO 1/4",
        "Pintuco",
        "Esmaltes",
        64,
        510,
        "ventas_y_stock",
        "cuarto",
        "Negro",
        "Brillante",
        "pintulux_negro",
        "pintulux negro",
        "pintulux, esmalte pintulux, pintulux negro",
        "cuarto, 1/4",
        "blanco, verde, mate, galon, cuñete",
        "Tengo Pintulux Negro. ¿Lo necesitas en Brillante o Mate?",
        "SI",
        "Mantener acabado en la pregunta cuando el cliente no lo indique explícitamente.",
    ],
    [
        "TPL_PTX_NGR_MAT_4",
        "PINTULUX NEGRO MATE CUARTO 1/4",
        "Pintuco",
        "Esmaltes",
        52,
        430,
        "ventas_y_stock",
        "cuarto",
        "Negro",
        "Mate",
        "pintulux_negro",
        "pintulux negro",
        "pintulux, esmalte pintulux, pintulux negro",
        "cuarto, 1/4",
        "blanco, verde, brillante, galon, cuñete",
        "Tengo Pintulux Negro. ¿Lo necesitas en Brillante o Mate?",
        "SI",
        "No resolver acabado por adivinanza. Si no lo dice el cliente, dejarlo abierto.",
    ],
    [
        "TPL_PTX_VBR_BRI_1",
        "PINTULUX VERDE BRONCE BRILLANTE GALON 1/1",
        "Pintuco",
        "Esmaltes",
        31,
        260,
        "ventas_y_stock",
        "galon",
        "Verde Bronce",
        "Brillante",
        "pintulux_verde_bronce",
        "pintulux verde bronce",
        "pintulux verde bronce, verde bronce, esmalte verde bronce",
        "galon, galón, 1/1",
        "bronce ref 86, bronce 86, negro, blanco",
        "Tengo Pintulux Verde Bronce. ¿Lo necesitas en brillante o en otra presentación?",
        "SI",
        "Color compuesto crítico. Nunca recortarlo a solo 'bronce'.",
    ],
    [
        "TPL_PTX_BR86_BRI_4",
        "PINTULUX BRONCE REF 86 BRILLANTE CUARTO 1/4",
        "Pintuco",
        "Esmaltes",
        27,
        220,
        "ventas_y_stock",
        "cuarto",
        "Bronce",
        "Brillante",
        "pintulux_bronce_ref_86",
        "pintulux bronce",
        "pintulux bronce, bronce 86, bronce ref 86",
        "cuarto, 1/4",
        "verde, verde bronce, negro, blanco",
        "Tengo Pintulux Bronce. ¿Te refieres al Bronce Ref 86 o al Verde Bronce?",
        "SI",
        "Fila crítica para evitar colisión con Verde Bronce.",
    ],
    [
        "TPL_SEG_ALCOBA",
        "CERRADURA SEGUREX ALCOBA CILINDRICA",
        "Segurex",
        "Cerrajeria",
        43,
        180,
        "ventas_y_stock",
        "und",
        None,
        None,
        "cerradura_segurex_alcoba",
        "cerradura segurex alcoba",
        "cerradura segurex, cerradura alcoba, chapa de pomo, cerradura de bola",
        None,
        "yale, principal, digital, sobreponer",
        "Tengo cerradura Segurex para alcoba. ¿La necesitas cilíndrica o estás buscando otro tipo de cerradura?",
        "SI",
        "Evitar mezclar con Yale y cerraduras principales.",
    ],
    [
        "TPL_SEG_BAÑO",
        "CERRADURA SEGUREX BAÑO CILINDRICA",
        "Segurex",
        "Cerrajeria",
        29,
        150,
        "ventas_y_stock",
        "und",
        None,
        None,
        "cerradura_segurex_baño",
        "cerradura segurex baño",
        "cerradura segurex, cerradura baño, chapa de baño",
        None,
        "alcoba, yale, principal, digital, sobreponer",
        "Tengo cerradura Segurex para baño. ¿Buscas la de baño o la de alcoba?",
        "SI",
        "Útil para separar alcoba y baño cuando el cliente solo dice 'cerradura segurex'.",
    ],
    [
        "TPL_AFIX_MAD_1K",
        "PEGANTE AFIX MADERA 1000GR",
        "Afix",
        "Adhesivos",
        57,
        340,
        "ventas_y_stock",
        "kilo",
        "Blanco",
        None,
        "pegante_afix_madera",
        "pegante afix madera",
        "pegante para madera, colbon, pegante blanco, pegante de carpintero",
        "kilo, 1000g, tarro",
        "boxer, amarillo, contacto, pvc",
        "Tengo Pegante Afix para madera. ¿Lo necesitas en 250gr, 500gr o 1000gr?",
        "SI",
        "No mezclar con pegantes de contacto ni PVC.",
    ],
    [
        "TPL_AFIX_MAD_500",
        "PEGANTE AFIX MADERA 500GR",
        "Afix",
        "Adhesivos",
        61,
        290,
        "ventas_y_stock",
        "und",
        "Blanco",
        None,
        "pegante_afix_madera",
        "pegante afix madera",
        "pegante para madera, colbon, pegante blanco, pegante de carpintero",
        "500g, tarro",
        "boxer, amarillo, contacto, pvc",
        "Tengo Pegante Afix para madera. ¿Lo necesitas en 250gr, 500gr o 1000gr?",
        "SI",
        "Mantener agrupación por familia y desambiguación por peso.",
    ],
    [
        "TPL_ART_P285_1",
        "ADHESIVO CONTACTO ARTECOLA PL-285 GALON 1/1",
        "Artecola",
        "Adhesivos",
        22,
        165,
        "ventas_y_stock",
        "galon",
        "Amarillo",
        None,
        "pegante_contacto_artecola",
        "pegante contacto artecola",
        "pegante amarillo, boxer, pegante de contacto, pl 285",
        "galon, galón, 1/1",
        "madera, blanco, pvc, afix",
        "Tengo Pegante de contacto Artecola. ¿Llevas cuarto, galón o lata?",
        "SI",
        "Debe competir solo contra adhesivos de contacto, no contra colbón o madera.",
    ],
]

columnas = [
    "producto_codigo",
    "descripcion_base",
    "marca",
    "categoria",
    "stock_total",
    "ventas_unidades_total",
    "prioridad_origen",
    "presentacion_canonica",
    "color_detectado",
    "acabado_detectado",
    "familia_consulta",
    "producto_padre_busqueda",
    "alias_producto",
    "alias_presentacion",
    "terminos_excluir",
    "pregunta_desambiguacion",
    "activo_agente",
    "observaciones_equipo",
]


df = pd.DataFrame(datos, columns=columnas)
print(df)